docs: update mkdocs operator
aquasecurity/trivy-operator pull request #138
Opened 2022-06-14 12:57 UTC by chen-keinan

Signed-off-by: chenk <hen.keinan@gmail.com>

## Description

## Related issues
- Close #128 

Remove this section if you don't have related PRs.

## Checklist
 - [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant

2022-06-15 13:16 UTC, josedonizetti requested changes

2022-06-15 13:16 UTC, josedonizetti commented on mkdocs.yml
> +    chart_version: "v0.0.6"
`chart_version` is duplicated, and the latest point to non existing version `v0.0.6`?

2022-06-15 13:22 UTC, josedonizetti commented on mkdocs.yml
> +
can we remove empty lines?

2022-06-15 13:32 UTC, merged

2022-06-18 08:06 UTC, itaysk commented
@chen-keinan @josedonizetti please sync with @AnaisUrlichs about this change. We need to make sure trivy-operator feels like part of Trivy