Replace code-generator with controller-gen
aquasecurity/trivy-operator pull request #209
Opened 2022-06-28 20:35 UTC by padlar

delete pkg/generated code

## Description

## Related issues
- #204

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2022-06-29 15:22 UTC, erikgb commented on Makefile
> +	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="pkg/apis/..."
```suggestion
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./pkg/apis/..."
```

I also think you need to run it, and commit the changes to `zz_generated.deepcopy.go` files. I would expect them to contain `// Code generated by deepcopy-gen. DO NOT EDIT.`

2022-06-29 20:49 UTC, erikgb requested changes

2022-06-29 20:49 UTC, erikgb commented on Makefile
> +# Set the default goal .DEFAULT_GOAL := build MAKEFLAGS += --no-print-directory DOCKER ?= docker KIND ?= kind
This is not an intentional change, or?

2022-06-29 20:49 UTC, erikgb commented on Makefile
> +CONTROLLER_TOOLS_VERSION ?= v0.9.1
```suggestion
CONTROLLER_TOOLS_VERSION ?= v0.9.2
```

New patched released today. 😄

2022-06-29 20:49 UTC, erikgb commented on hack/tools.go
> -	_ "github.com/onsi/ginkgo/ginkgo"
I see the integration tests are failing, and I think it is because you removed this. Can you just remove the line with code-generator import?

2022-06-30 11:23 UTC, padlar commented on Makefile
> +# Set the default goal .DEFAULT_GOAL := build MAKEFLAGS += --no-print-directory DOCKER ?= docker KIND ?= kind
reverted the change

2022-06-30 11:23 UTC, padlar commented on Makefile
> +CONTROLLER_TOOLS_VERSION ?= v0.9.1
updated the version

2022-06-30 12:40 UTC, chen-keinan commented
@padlar thank you for the contribution  ,  pls update the contribution guide with instruction for usage

2022-06-30 17:17 UTC, josedonizetti approved these changes
This looks good, love the cleanup of not used code. Thanks @padlar !

2022-06-30 17:35 UTC, josedonizetti commented
Question, this PR is not adding the markers to generate CRDs, is the idea to follow up with a PR for it?

2022-06-30 18:02 UTC, padlar commented
@josedonizetti yes this PR addresses pt1 in issue 204. There will be follow up PRs that will address the other 2 points.

2022-06-30 18:33 UTC, padlar commented on Makefile
> +LOCALBIN ?= $(shell pwd)/bin
filed #231

2022-07-03 10:08 UTC, chen-keinan commented
LGTM!

2022-07-03 10:08 UTC, merged