Add extraEnv option to Helm chart
aquasecurity/trivy-operator pull request #2288
Opened 2024-10-17 15:41 UTC by gnadaban

## Description

This is a small fix to account for the lack of ability to add extra env vars to the trivy-operator deployment.
This allows specifying eg. AWS IAM session names and other options for eg. secret injection.

## Related issues
- Close #2287 

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2025-01-10 01:34 UTC, simar7 approved these changes
lgtm, @afdesk could you take a look as well?

2025-01-10 01:34 UTC, simar7 commented
@gnadaban could you resolve the merge conflict?

2025-01-10 11:03 UTC, afdesk requested changes
@gnadaban thanks a lot for your contribution! It's really nice.
I left some small comments

2025-01-10 14:56 UTC, gnadaban commented on deploy/helm/values.yaml
> +  {}
Because of auto-formatting YAML files when using an IDE that does this.
Is it a concern?

2025-01-10 15:00 UTC, gnadaban commented on deploy/helm/values.yaml
> +  {}
I will reindent the comments below to make sure it works correctly with autoformatting.

2025-01-13 20:19 UTC, gnadaban commented
Hi @afdesk , can you please re:re?

2025-01-14 05:45 UTC, afdesk approved these changes
LGTM! thanks!

2025-01-15 06:06 UTC, merged

2025-02-06 09:49 UTC, Xeroxxx commented
@afdesk Why has the helm chart version not been bumped to 0.24.0 with the new release?