fix: getting imagePullSecrets should fail only if not exist in pod speec and service account
aquasecurity/trivy-operator pull request #270
Opened 2022-07-10 10:04 UTC by chen-keinan

Signed-off-by: chenk <hen.keinan@gmail.com>
## Description
Getting imagePullSecrets should fail only if not exist in pod spec and service account

## Related issues
- Close #266 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.

2022-07-10 10:29 UTC, erikgb requested changes
One suggestion and a couple of nits.

2022-07-10 10:29 UTC, erikgb commented on pkg/kube/secrets.go
> +		if err != nil && !k8sapierror.IsNotFound(err) {
Wouldn't it be better to just `continue` if `k8sapierror.IsNotFound(err)`? Then you avoid protecting the `append`.

2022-07-10 10:29 UTC, erikgb commented on pkg/kube/secrets.go
> +		return nil, fmt.Errorf("failed to list secrtes by imagePullSecrets ref %v and service account %s", spec.ImagePullSecrets, serviceAccountName)
```suggestion
		return nil, fmt.Errorf("failed to list secrets by imagePullSecrets ref %v and service account %s", spec.ImagePullSecrets, serviceAccountName)
```

2022-07-10 10:29 UTC, erikgb commented on pkg/kube/testdata/fixture/sa_with_image_pull_secret.json
> +}
```suggestion
}

```

2022-07-10 10:29 UTC, erikgb commented on pkg/kube/testdata/fixture/sa_without_image_pull_secret.json
> +}
```suggestion
}

```

2022-07-10 11:47 UTC, erikgb commented on pkg/kube/secrets.go
> -		secrets = append(secrets, secret)
This statement should be be deleted.

2022-07-11 10:37 UTC, erikgb commented
@chen-keinan I don't understand the logic in `impactPullSecretDefineAndNoSecretsFound` and why we need it. This code needs cleanup IMO, and I have drafted some here: https://github.com/aquasecurity/trivy-operator/pull/276/files. But your tests added in this PR is good!

2022-07-11 11:04 UTC, erikgb commented
> We want it to fail if imagePullSecrets ref define , but secret do not exist , at least one secret must exist

Ok, I see. Is that how Kubernetes works? Ref.

> Exactly As the kubernetes pods controller, just ignore the missing secret.

2022-07-11 11:44 UTC, josedonizetti approved these changes

2022-07-11 11:59 UTC, merged