fix: skip replicaSet scanning when there is no active pod
aquasecurity/trivy-operator pull request #475
Opened 2022-08-30 11:27 UTC by chen-keinan

Signed-off-by: chenk <hen.keinan@gmail.com>

## Description

## Related issues
- Close #387 

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2022-08-30 23:59 UTC, josedonizetti requested changes
@chen-keinan A couple things to discuss/fix related to this PR.

1 - if you apply a statefulset, with zero replicas, it still is scanned and generate reports
2 - if you apply a replication controller with zero replicas, it still is scanned and generate reports
3 - if you apply a replica set with zero or more replicas we get a `segmentation violation`
```
goroutine 1829 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/josedonizetti/code/aquasecurity/trivy-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1e1d4e0, 0x3579bc0})
	/snap/go/9952/src/runtime/panic.go:838 +0x207
github.com/aquasecurity/trivy-operator/pkg/operator/workload.SkipProcessing({0x2566000, 0xc000d1be60}, {0x2580430?, 0xc0019d2d80?}, {{0x256e1f0, 0xc000133630}, {0x254b4e0, 0xc000468b60}}, 0x1, {{0x25691f0, ...}, ...})
	/home/josedonizetti/code/aquasecurity/trivy-operator/pkg/operator/workload/helper.go:23 +0x3a7
github.com/aquasecurity/trivy-operator/pkg/configauditreport/controller.(*ResourceController).reconcileResource.func1({0x2566000, 0xc000d1be60}, {{{0xc0019b8b50, 0x7}, {0xc0019b8b38, 0x8}}})
	/home/josedonizetti/code/aquasecurity/trivy-operator/pkg/configauditreport/controller/controller.go:186 +0x45f
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0x30?, {0x2566000?, 0xc000d1be60?}, {{{0xc0019b8b50?, 0x10?}, {0xc0019b8b38?, 0x40f3e7?}}})

4 - when we apply a deployment with replicas, and then scale it down, the reports are supposed to be cleaned? (when the TTL expire?)

Besides the `segmentation violation` which I think must be fixed, we need to think, should we be consistent here? if we don't scan deployments with zero replicas, the same should be true for statefulsets, replication controllers and replicasets, right?
```

2022-08-31 06:20 UTC, chen-keinan commented
> @chen-keinan A couple things to discuss/fix related to this PR.
> 
> 1 - if you apply a statefulset, with zero replicas, it still is scanned and generate reports 2 - if you apply a replication controller with zero replicas, it still is scanned and generate reports 3 - if you apply a replica set with zero or more replicas we get a `segmentation violation`
> 4 - when we apply a deployment with replicas, and then scale it down, the reports are supposed to be cleaned? (when the TTL expire?)
> 
> Besides the `segmentation violation` which I think must be fixed, we need to think, should we be consistent here? if we don't scan deployments with zero replicas, the same should be true for statefulsets, replication controllers and replicasets, right?

1-2 : meant to be done on  a separate PR however I have no problem making it here as its a small change
3. fixed.
4. reports are not automatically deleted as it on `replicaset` and not on `pods` when TTL hit (24h) should be deleted

2022-08-31 14:25 UTC, josedonizetti reviewed
@chen-keinan I don't mind if we fix sts, rc on another PR. Though there still a critical bug here for me, we are not getting a panic anymore, but if you apply a `replicaset` directly, no report is created, even though we have a new pod running on the cluster. eg:

```
$ kubectl  get pods
NAME             READY   STATUS    RESTARTS   AGE
frontend-hjsm8   1/1     Running   0          20s

$ kubectl  get rs
NAME       DESIRED   CURRENT   READY   AGE
frontend   1         1         1       116s

$ kubectl get vuln,exposedsecrets,configaudit
No resources found in default namespace.

```

2022-08-31 17:27 UTC, josedonizetti commented on pkg/operator/workload/helper.go
> +		}
This piece of code is getting repeated 3 times, perhaps we can refactor later and extract it to a func.

2022-08-31 17:27 UTC, josedonizetti approved these changes

2022-09-01 04:31 UTC, merged